spring:
  datasource:
    db-previous: # Configuración del primer DataSource
      url: jdbc:mysql://localhost:3306/primary_database
      username: primary_user
      password: primary_password
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: PrimaryHikariPool
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 30000
        max-lifetime: 600000
        connection-timeout: 30000
    db-production: # Configuración del segundo DataSource
      url: jdbc:mysql://localhost:3306/secondary_database
      username: secondary_user
      password: secondary_password
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: SecondaryHikariPool
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 30000
        max-lifetime: 600000
        connection-timeout: 30000

# Opcional: Configuración de JPA si usas repositorios
jpa:
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQLDialect

